from enum import IntEnum


class BoardEventTypes(IntEnum):
    INVALID_MOVE = 0
    INVALID_MOVE_PIECE_CANNOT_DO_MOVE = 1
    INVALID_MOVE_PIECE_CANNOT_DO_THIS_ATTACK = 2
    INVALID_MOVE_ATTACKS_MUST_BE_DONE_ON_ENEMIES = 3
    PIECE_BLOCKED_BY_ALLY = 4
    PIECE_BLOCKED_BY_ENEMY = 5
    PIECE_MOVED_TO_SPACE = 6
    PIECE_MOVED_TO_SPACE_AND_KILLED = 7,
    MOVE_CAN_ONLY_BE_MADE_TO_EMPTY_SPACE = 8
    INVALID_MOVE_WOULD_PUT_YOU_IN_CHECK = 9,
    PIECE_MOVED_TO_SPACE_AND_KILLED_KING = 10
