import enum


class ChessMessageType(enum.Enum):
    BASE = 0
    MOVE = 1
    CLIENT_PLAYER_JOIN_HOST_LOBBY = 2
    CLIENT_PLAYER_JOIN_LOBBY = 3
    PLAYER_TURN_STARTED = 4
    INVALID_PLAYER_MOVE = 5
    INPUT_INPUT_PIECE_CAN_BE_UPGRADED = 6
    OUTPUT_INPUT_PIECE_CAN_BE_UPGRADED = 7


